fixtures:
  repositories:
    common:
      repo: 'https://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.6.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '2.1.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
  symlinks:
    bind: "#{source_dir}"
